AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Messenger Stack

Parameters:
  ApplicationName:
    Type: String
    Default: 'messenger'

Resources:
  WebSocketApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ '/', [ '/aws/apigateway', !Ref ApplicationName ] ]
      RetentionInDays: 1

  WebSocketApiGateway:
    Type: AWS::ApiGatewayV2::Api
    DependsOn: 'WebSocketApiGatewayLogGroup'
    Properties:
      Name: !Ref ApplicationName
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: dev
      AutoDeploy: true
      ApiId: !Ref WebSocketApiGateway

  MessengerOnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: hrach-lambda-dev-build
        Key: messenger.onconnect.zip
      Handler: bootstrap
      FunctionName: messenger-onconnect
      Architectures:
        - x86_64
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PATCH
                - apigateway:PUT 
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - '*'                            


  MessengerOnConnectFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: 'MessengerOnConnectFunction'
    Properties:
      RetentionInDays: 1
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref MessengerOnConnectFunction ] ]
  
  MessengerOnConnectInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: MessengerOnConnectFunction
    Properties:
      FunctionName:
        Ref: "MessengerOnConnectFunction"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApiGateway}/*' 
  
  MessengerOnConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      Description: OnConnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MessengerOnConnectFunction.Arn}/invocations
  MessengerOnConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: OnConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MessengerOnConnectIntegration
  
  MessengerOnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: hrach-lambda-dev-build
        Key: messenger.ondisconnect.zip
      Handler: bootstrap
      FunctionName: messenger-ondisconnect
      Architectures:
        - x86_64
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PATCH
                - apigateway:PUT 
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - '*'                            

  MessengerOnDisconnectFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: 'MessengerOnDisconnectFunction'
    Properties:
      RetentionInDays: 1
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref MessengerOnDisconnectFunction ] ]
  
  MessengerOnDisconnectInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: MessengerOnDisconnectFunction
    Properties:
      FunctionName:
        Ref: "MessengerOnDisconnectFunction"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApiGateway}/*' 
  
  MessengerOnDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      Description: OnDisconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MessengerOnDisconnectFunction.Arn}/invocations
  
  MessengerOnDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: OnDisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MessengerOnDisconnectIntegration
   
  MessengerRoomCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: hrach-lambda-dev-build
        Key: messenger.roomcreate.zip
      Handler: bootstrap
      FunctionName: messenger-room-create
      Architectures:
        - x86_64
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PATCH
                - apigateway:PUT 
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
                - execute-api:ManageConnections
                - execute-api:Invoke
              Resource:
                - '*'                            


  MessengerRoomCreateFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: 'MessengerRoomCreateFunction'
    Properties:
      RetentionInDays: 1
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref MessengerRoomCreateFunction ] ]
  
  MessengerRoomCreateInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: MessengerRoomCreateFunction
    Properties:
      FunctionName:
        Ref: "MessengerRoomCreateFunction"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApiGateway}/*' 
  
  MessengerRoomCreateIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      Description: Room Create Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MessengerRoomCreateFunction.Arn}/invocations
  MessengerRoomCreateRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: createRoom
      AuthorizationType: NONE
      OperationName: RoomCreateRoute 
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MessengerRoomCreateIntegration
  
  MessengerSendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: hrach-lambda-dev-build
        Key: messenger.sendmessage.zip
      Handler: bootstrap
      FunctionName: messenger-send-message
      Architectures:
        - x86_64
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PATCH
                - apigateway:PUT 
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
                - execute-api:ManageConnections
                - execute-api:Invoke
              Resource:
                - '*'                            
                - 'arn:aws:execute-api:*:*:**/@connections/*'

  MessengerSendMessageFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: 'MessengerSendMessageFunction'
    Properties:
      RetentionInDays: 1
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref MessengerSendMessageFunction ] ]
  
  MessengerSendMessageInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: MessengerSendMessageFunction
    Properties:
      FunctionName:
        Ref: "MessengerSendMessageFunction"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApiGateway}/*' 
  
  MessengerSendMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      Description: Room Create Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MessengerSendMessageFunction.Arn}/invocations
  
  MessengerSendMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: send
      AuthorizationType: NONE
      OperationName: SendMessageRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MessengerSendMessageIntegration
  
  MessengerEditFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: hrach-lambda-dev-build
        Key: messenger.edit.zip
      Handler: bootstrap
      FunctionName: messenger-edit
      Architectures:
        - x86_64
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PATCH
                - apigateway:PUT 
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
                - execute-api:ManageConnections
                - execute-api:Invoke
              Resource:
                - '*'                            
                - 'arn:aws:execute-api:*:*:**/@connections/*'

  MessengerEditFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: 'MessengerEditFunction'
    Properties:
      RetentionInDays: 1
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref MessengerEditFunction ] ]
  
  MessengerEditInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: MessengerEditFunction
    Properties:
      FunctionName:
        Ref: "MessengerEditFunction"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApiGateway}/*' 
  
  MessengerEditIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      Description: Edit Mesages 
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MessengerEditFunction.Arn}/invocations
  
  MessengerEditRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: edit
      AuthorizationType: NONE
      OperationName: EditMessageRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MessengerEditIntegration 
  
 
  MessengerFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: hrach-lambda-dev-build
        Key: messenger.fetch.zip
      Handler: bootstrap
      FunctionName: messenger-fetch
      Architectures:
        - x86_64
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:POST
                - apigateway:GET
                - apigateway:PATCH
                - apigateway:PUT 
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
                - execute-api:ManageConnections
                - execute-api:Invoke
              Resource:
                - '*'                            
                - 'arn:aws:execute-api:*:*:**/@connections/*'

  MessengerFetchFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: 'MessengerFetchFunction'
    Properties:
      RetentionInDays: 1
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref MessengerFetchFunction ] ]
  
  MessengerFetchInvokePermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: MessengerFetchFunction
    Properties:
      FunctionName:
        Ref: "MessengerFetchFunction"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApiGateway}/*' 
  
  MessengerFetchIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      Description: Fetch Mesages 
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MessengerFetchFunction.Arn}/invocations
  
  MessengerFetchRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: fetch
      AuthorizationType: NONE
      OperationName: FetchMessagesRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MessengerFetchIntegration 
  
  MessengerDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'messenger'
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S' 
        - AttributeName: 'gsi1pk'
          AttributeType: 'S'
        - AttributeName: 'gsi1sk'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'pk'
          KeyType: HASH
        - AttributeName: 'sk'
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: 'gsi1'
          KeySchema:
            - AttributeName: 'gsi1pk'
              KeyType: HASH
            - AttributeName: 'gsi1sk'
              KeyType: RANGE  
          Projection:
            ProjectionType: ALL
